services:
  userDB:
    image: postgres:16
    container_name: vnbike-userdb
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    ports:
      - "${PG_DBPORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  it4DB:
    image: mysql:8.3.0
    container_name: it4today-db
    restart: always
    ports:
      - '${MYSQL_PORT}:3306'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  pg-data:
  db-data:
